spring.application.name=day19
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/app_db
spring.datasource.username=app
spring.datasource.password=secret
spring.jpa.hibernate.ddl-auto=update
